package id.mncinnovation.identification.core.common

const val EXTRA_IMAGE_URI = "EXTRA_IMAGE_URI"
const val EXTRA_LIST_IMAGE_URI = "EXTRA_LIST_IMAGE_URI"
const val EXTRA_IMAGE_URI_2 = "EXTRA_IMAGE_URI_2"
const val EXTRA_IMAGE_URI_3 = "EXTRA_IMAGE_URI_3"
const val EXTRA_KTP = "EXTRA_KTP"
const val EXTRA_WITH_FLASH = "EXTRA_WITH_FLASH"
const val EXTRA_CAMERA_ONLY = "EXTRA_CAMERA_ONLY"
const val EXTRA_ERROR_MESSAGE = "EXTRA_ERROR_MESSAGE"
const val EXTRA_RESULT = "EXTRA_RESULT"
const val CAPTURE_EKTP_REQUEST_CODE = 102